Repository gdirk07/PokemonChecker, pull requests merged in 2021-11, with the labels that each got.

#26 Updated fetch all pokemon service to filter unwanted results
  pokemon-checker/src/App.tsx
  pokemon-checker/src/services/PokemonService.ts
Labels: bug, Cleanup

#31 Updated PokemonDisplay component rendering component
  pokemon-checker/src/components/PokemonDisplay/PokemonDisplay.tsx
  pokemon-checker/src/components/PokemonDisplay/PokemonImageDisplay.tsx
  pokemon-checker/src/components/PokemonDisplay/PokemonInfoDisplay.tsx
  pokemon-checker/tsconfig.json
Labels: Cleanup, Refactor

#32 Implemented a basic cache for holding the pokemon names
  pokemon-checker/src/App.tsx
  pokemon-checker/src/DataTransferObjects/MoveDTO.ts
  pokemon-checker/src/DataTransferObjects/PokemonDTO.ts
  pokemon-checker/src/components/PokemonDisplay/PokemonDisplay.tsx
  pokemon-checker/src/components/PokemonSearch/PokemonSearchResults.tsx
  pokemon-checker/src/constants/Time.ts
  pokemon-checker/src/factories/PokemonFactory.ts
  pokemon-checker/src/interfaces/PokemonData.ts
  pokemon-checker/src/repositories/PokemonRepository.ts
  pokemon-checker/src/services/PokemonService.ts
Labels: enhancement, Refactor
